/*
 Navicat Premium Data Transfer

 Source Server         : ScoreManager
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 30/08/2022 15:59:32
*/


-- ----------------------------
-- Table structure for EDU_ACTION
-- ----------------------------
DROP TABLE "SCOTT"."EDU_ACTION";
CREATE TABLE "SCOTT"."EDU_ACTION" (
  "ID" NUMBER NOT NULL,
  "NAME" NVARCHAR2(20),
  "DESCRIPTION" NVARCHAR2(20),
  "ADDTIME" DATE DEFAULT SYSDATE  NOT NULL,
  "ISENABLE" CHAR(1 CHAR) DEFAULT 1  NOT NULL,
  "CONFIG" NVARCHAR2(500)
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_ACTION"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_ACTION"."NAME" IS '权限名称';
COMMENT ON COLUMN "SCOTT"."EDU_ACTION"."DESCRIPTION" IS '权限描述';
COMMENT ON COLUMN "SCOTT"."EDU_ACTION"."ADDTIME" IS '添加时间';
COMMENT ON COLUMN "SCOTT"."EDU_ACTION"."ISENABLE" IS '是否启用 0：不启用 1：启用 默认启用';
COMMENT ON COLUMN "SCOTT"."EDU_ACTION"."CONFIG" IS '权限配置详情  json字符串';

-- ----------------------------
-- Records of EDU_ACTION
-- ----------------------------
INSERT INTO "SCOTT"."EDU_ACTION" VALUES ('1', '试卷管理', '创建、修改试卷', TO_DATE('2022-08-30 15:44:36', 'SYYYY-MM-DD HH24:MI:SS'), '1', '{"ExamManageMenu":[{"Url":"/ExaminPaper/ExaminPaperList","Title":"试卷列表","Label":"试卷列表"}]}');
INSERT INTO "SCOTT"."EDU_ACTION" VALUES ('2', '阅卷', '考试阅卷', TO_DATE('2022-08-30 15:47:20', 'SYYYY-MM-DD HH24:MI:SS'), '1', '{"ExamManageMenu":[{"Url":"/Exam/MarkPaperList","Title":"考试阅卷","Label":"考试阅卷"}]}');
INSERT INTO "SCOTT"."EDU_ACTION" VALUES ('3', '查看成绩', '查看班级成绩', TO_DATE('2022-08-30 15:49:41', 'SYYYY-MM-DD HH24:MI:SS'), '1', '{"ExamManageMenu":[{"Url":"/ClassExamin/ClassExaminList","Title":"班级成绩","Label":"班级成绩"}]}');
INSERT INTO "SCOTT"."EDU_ACTION" VALUES ('4', '考试管理', '创建、修改考试信息', TO_DATE('2022-08-30 15:53:10', 'SYYYY-MM-DD HH24:MI:SS'), '1', '{"ExamManageMenu":[{"Url":"/Exam/ExamList","Title":"考试列表","Label":"考试列表"}]}');
INSERT INTO "SCOTT"."EDU_ACTION" VALUES ('5', '处理申诉', '学科老师处理学生的申诉', TO_DATE('2022-08-30 15:56:58', 'SYYYY-MM-DD HH24:MI:SS'), '1', '{"ExamManageMenu":[{"Url":"/Appeal/AppealList","Title":"申诉处理","Label":"申诉处理"}]}');

-- ----------------------------
-- Table structure for EDU_APPEAL
-- ----------------------------
DROP TABLE "SCOTT"."EDU_APPEAL";
CREATE TABLE "SCOTT"."EDU_APPEAL" (
  "ID" NUMBER NOT NULL,
  "SCOREDETAILID" NUMBER(38,0) DEFAULT 0  NOT NULL,
  "REASON" NVARCHAR2(100),
  "RESULT" NVARCHAR2(100),
  "HANDLETEACHERID" NUMBER
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_APPEAL"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_APPEAL"."SCOREDETAILID" IS '得分详情id';
COMMENT ON COLUMN "SCOTT"."EDU_APPEAL"."REASON" IS '申诉内容';
COMMENT ON COLUMN "SCOTT"."EDU_APPEAL"."RESULT" IS '申诉结果';
COMMENT ON COLUMN "SCOTT"."EDU_APPEAL"."HANDLETEACHERID" IS '处理老师id';
COMMENT ON TABLE "SCOTT"."EDU_APPEAL" IS '学生成绩申诉';

-- ----------------------------
-- Records of EDU_APPEAL
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_CLASS
-- ----------------------------
DROP TABLE "SCOTT"."EDU_CLASS";
CREATE TABLE "SCOTT"."EDU_CLASS" (
  "ID" NUMBER NOT NULL,
  "NAME" NVARCHAR2(10) NOT NULL,
  "ISENABLE" CHAR(1 CHAR) DEFAULT 1  NOT NULL,
  "ADDTIME" DATE DEFAULT sysdate  NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_CLASS"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_CLASS"."NAME" IS '名称';
COMMENT ON COLUMN "SCOTT"."EDU_CLASS"."ISENABLE" IS '是否可用 0：不可用 1：可用  默认1';
COMMENT ON COLUMN "SCOTT"."EDU_CLASS"."ADDTIME" IS '添加时间';

-- ----------------------------
-- Records of EDU_CLASS
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_CLASS_TEACHER
-- ----------------------------
DROP TABLE "SCOTT"."EDU_CLASS_TEACHER";
CREATE TABLE "SCOTT"."EDU_CLASS_TEACHER" (
  "TEACHERID" NUMBER NOT NULL,
  "CLASSID" NUMBER NOT NULL,
  "ROLEID" NUMBER
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_CLASS_TEACHER"."TEACHERID" IS '教师Id';
COMMENT ON COLUMN "SCOTT"."EDU_CLASS_TEACHER"."CLASSID" IS '班级Id';
COMMENT ON COLUMN "SCOTT"."EDU_CLASS_TEACHER"."ROLEID" IS '教师角色id';

-- ----------------------------
-- Records of EDU_CLASS_TEACHER
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_EXAM
-- ----------------------------
DROP TABLE "SCOTT"."EDU_EXAM";
CREATE TABLE "SCOTT"."EDU_EXAM" (
  "ID" NUMBER NOT NULL,
  "SUBJECTID" NUMBER NOT NULL,
  "NAME" NVARCHAR2(20),
  "EDU_TEACHERID" NUMBER,
  "ISPUB" CHAR(1 BYTE) DEFAULT 0,
  "STARTTIME" DATE DEFAULT sysdate,
  "ENDTIME" DATE DEFAULT sysdate,
  "CLASSID" NUMBER,
  "MARKPAPERTEACHERID" NUMBER DEFAULT 0
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_EXAM"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_EXAM"."SUBJECTID" IS '科目Id';
COMMENT ON COLUMN "SCOTT"."EDU_EXAM"."NAME" IS '考试名称';
COMMENT ON COLUMN "SCOTT"."EDU_EXAM"."EDU_TEACHERID" IS '教务老师Id';
COMMENT ON COLUMN "SCOTT"."EDU_EXAM"."ISPUB" IS '是否已发布 0：未发布 1：已发布 默认0';
COMMENT ON COLUMN "SCOTT"."EDU_EXAM"."STARTTIME" IS '考试开始时间';
COMMENT ON COLUMN "SCOTT"."EDU_EXAM"."ENDTIME" IS '考试结束时间';
COMMENT ON COLUMN "SCOTT"."EDU_EXAM"."CLASSID" IS '班级id';
COMMENT ON COLUMN "SCOTT"."EDU_EXAM"."MARKPAPERTEACHERID" IS '阅卷老师id';

-- ----------------------------
-- Records of EDU_EXAM
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_EXAMDETIAL
-- ----------------------------
DROP TABLE "SCOTT"."EDU_EXAMDETIAL";
CREATE TABLE "SCOTT"."EDU_EXAMDETIAL" (
  "ID" NUMBER NOT NULL,
  "STUDENTID" NUMBER NOT NULL,
  "EXAMID" NUMBER NOT NULL,
  "SCORE" FLOAT(126) DEFAULT 0,
  "STATUS" NUMBER DEFAULT 0
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_EXAMDETIAL"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMDETIAL"."STUDENTID" IS '学生id';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMDETIAL"."EXAMID" IS '考试Id';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMDETIAL"."SCORE" IS '分数';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMDETIAL"."STATUS" IS '状态 0：未开始 1:考完？ 2：阅卷完毕 默认0';

-- ----------------------------
-- Records of EDU_EXAMDETIAL
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_EXAMINE_PAPER
-- ----------------------------
DROP TABLE "SCOTT"."EDU_EXAMINE_PAPER";
CREATE TABLE "SCOTT"."EDU_EXAMINE_PAPER" (
  "ID" NUMBER NOT NULL,
  "EXAMINEID" NUMBER,
  "DESCRIPTION" NVARCHAR2(100),
  "NAME" VARCHAR2(100 BYTE) DEFAULT '默认试卷',
  "ISENABLE" CHAR(1 BYTE) DEFAULT '0'
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_EXAMINE_PAPER"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMINE_PAPER"."EXAMINEID" IS '考试ID';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMINE_PAPER"."DESCRIPTION" IS '试卷描述';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMINE_PAPER"."NAME" IS '试卷名称';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMINE_PAPER"."ISENABLE" IS '是否启用 0：不启用 1：启用 默认不启用';
COMMENT ON TABLE "SCOTT"."EDU_EXAMINE_PAPER" IS '考试试卷';

-- ----------------------------
-- Records of EDU_EXAMINE_PAPER
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_EXAMQUESTIONS
-- ----------------------------
DROP TABLE "SCOTT"."EDU_EXAMQUESTIONS";
CREATE TABLE "SCOTT"."EDU_EXAMQUESTIONS" (
  "ID" NUMBER NOT NULL,
  "PAPERID" NUMBER,
  "ORDERINDEX" NUMBER,
  "DESCRIPTION" NVARCHAR2(200) DEFAULT '',
  "RESULT" NVARCHAR2(200) DEFAULT '',
  "SCORE" NUMBER DEFAULT 0.0
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_EXAMQUESTIONS"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMQUESTIONS"."PAPERID" IS '试卷id';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMQUESTIONS"."ORDERINDEX" IS '试题序号';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMQUESTIONS"."DESCRIPTION" IS '试题描述';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMQUESTIONS"."RESULT" IS '试题答案';
COMMENT ON COLUMN "SCOTT"."EDU_EXAMQUESTIONS"."SCORE" IS '试题分数';
COMMENT ON TABLE "SCOTT"."EDU_EXAMQUESTIONS" IS '试卷题目';

-- ----------------------------
-- Records of EDU_EXAMQUESTIONS
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_ROLE
-- ----------------------------
DROP TABLE "SCOTT"."EDU_ROLE";
CREATE TABLE "SCOTT"."EDU_ROLE" (
  "ID" NUMBER NOT NULL,
  "DESCRIPTION" NVARCHAR2(30),
  "NAME" NVARCHAR2(10),
  "ADDTIME" DATE DEFAULT SYSDATE  NOT NULL,
  "ISENABLE" CHAR(1 BYTE) DEFAULT 1  NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_ROLE"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_ROLE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SCOTT"."EDU_ROLE"."NAME" IS '角色名称';
COMMENT ON COLUMN "SCOTT"."EDU_ROLE"."ADDTIME" IS '添加时间';
COMMENT ON COLUMN "SCOTT"."EDU_ROLE"."ISENABLE" IS '是否启用 0：不启用 1：启用 默认启用';

-- ----------------------------
-- Records of EDU_ROLE
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_ROLE_ACTION
-- ----------------------------
DROP TABLE "SCOTT"."EDU_ROLE_ACTION";
CREATE TABLE "SCOTT"."EDU_ROLE_ACTION" (
  "ROLEID" NUMBER NOT NULL,
  "ACTIONID" NUMBER NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_ROLE_ACTION"."ROLEID" IS '角色id';
COMMENT ON COLUMN "SCOTT"."EDU_ROLE_ACTION"."ACTIONID" IS '权限id';

-- ----------------------------
-- Records of EDU_ROLE_ACTION
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_SCOREDETAIL
-- ----------------------------
DROP TABLE "SCOTT"."EDU_SCOREDETAIL";
CREATE TABLE "SCOTT"."EDU_SCOREDETAIL" (
  "ID" NUMBER NOT NULL,
  "EXAMDETAILID" NUMBER(38,0) DEFAULT 0  NOT NULL,
  "QUESTIONID" NUMBER(38,0) DEFAULT 0  NOT NULL,
  "SCORE" NUMBER DEFAULT 0  NOT NULL,
  "ANSWER" NVARCHAR2(200)
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_SCOREDETAIL"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_SCOREDETAIL"."EXAMDETAILID" IS '考试详情id';
COMMENT ON COLUMN "SCOTT"."EDU_SCOREDETAIL"."QUESTIONID" IS '考试题目id';
COMMENT ON COLUMN "SCOTT"."EDU_SCOREDETAIL"."SCORE" IS '得分';
COMMENT ON COLUMN "SCOTT"."EDU_SCOREDETAIL"."ANSWER" IS '回答';
COMMENT ON TABLE "SCOTT"."EDU_SCOREDETAIL" IS '考试得分详情';

-- ----------------------------
-- Records of EDU_SCOREDETAIL
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_STUDENT
-- ----------------------------
DROP TABLE "SCOTT"."EDU_STUDENT";
CREATE TABLE "SCOTT"."EDU_STUDENT" (
  "ID" NUMBER NOT NULL,
  "CLASSID" NUMBER,
  "NAME" NVARCHAR2(10),
  "USERID" NUMBER,
  "ISDELETE" CHAR(1 CHAR) DEFAULT '1'  NOT NULL,
  "STUDYCODE" VARCHAR2(20 BYTE)
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_STUDENT"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_STUDENT"."CLASSID" IS '班级id';
COMMENT ON COLUMN "SCOTT"."EDU_STUDENT"."NAME" IS '姓名';
COMMENT ON COLUMN "SCOTT"."EDU_STUDENT"."USERID" IS '用户id';
COMMENT ON COLUMN "SCOTT"."EDU_STUDENT"."ISDELETE" IS '是否已删除 0：已删除 1：未删除 默认未删除';
COMMENT ON COLUMN "SCOTT"."EDU_STUDENT"."STUDYCODE" IS '学号';

-- ----------------------------
-- Records of EDU_STUDENT
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_SUBJECT
-- ----------------------------
DROP TABLE "SCOTT"."EDU_SUBJECT";
CREATE TABLE "SCOTT"."EDU_SUBJECT" (
  "ID" NUMBER NOT NULL,
  "NAME" NVARCHAR2(20),
  "DESCRIPTION" NVARCHAR2(20),
  "ISENABLE" CHAR(1 CHAR) DEFAULT 1  NOT NULL,
  "ADDTIME" DATE DEFAULT sysdate  NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_SUBJECT"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_SUBJECT"."NAME" IS '学科名称';
COMMENT ON COLUMN "SCOTT"."EDU_SUBJECT"."DESCRIPTION" IS '学科描述';
COMMENT ON COLUMN "SCOTT"."EDU_SUBJECT"."ISENABLE" IS '是否启用 0 不启用 1 启用默认启用';
COMMENT ON COLUMN "SCOTT"."EDU_SUBJECT"."ADDTIME" IS '添加时间';

-- ----------------------------
-- Records of EDU_SUBJECT
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_SUGGESTIONS
-- ----------------------------
DROP TABLE "SCOTT"."EDU_SUGGESTIONS";
CREATE TABLE "SCOTT"."EDU_SUGGESTIONS" (
  "ID" NUMBER NOT NULL,
  "TEACHERID" NUMBER NOT NULL,
  "STUDENTID" NUMBER NOT NULL,
  "CONTENT" NVARCHAR2(200),
  "EXAMDETAILID" NUMBER NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_SUGGESTIONS"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_SUGGESTIONS"."TEACHERID" IS '教师Id';
COMMENT ON COLUMN "SCOTT"."EDU_SUGGESTIONS"."STUDENTID" IS '学生id';
COMMENT ON COLUMN "SCOTT"."EDU_SUGGESTIONS"."CONTENT" IS '建议内容';
COMMENT ON COLUMN "SCOTT"."EDU_SUGGESTIONS"."EXAMDETAILID" IS '考试Id';

-- ----------------------------
-- Records of EDU_SUGGESTIONS
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_TEACHER
-- ----------------------------
DROP TABLE "SCOTT"."EDU_TEACHER";
CREATE TABLE "SCOTT"."EDU_TEACHER" (
  "ID" NUMBER NOT NULL,
  "EMAIL_ADDRESS" VARCHAR2(20 CHAR),
  "PHONE_NUMBER" VARCHAR2(11 CHAR),
  "NAME" NVARCHAR2(10) NOT NULL,
  "USERID" NUMBER NOT NULL,
  "SUBJECTID" NUMBER,
  "ISDELETE" CHAR(1 BYTE) DEFAULT 1  NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_TEACHER"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_TEACHER"."EMAIL_ADDRESS" IS '邮箱地址';
COMMENT ON COLUMN "SCOTT"."EDU_TEACHER"."PHONE_NUMBER" IS '电话号码';
COMMENT ON COLUMN "SCOTT"."EDU_TEACHER"."NAME" IS '老师姓名';
COMMENT ON COLUMN "SCOTT"."EDU_TEACHER"."USERID" IS '用户Id';
COMMENT ON COLUMN "SCOTT"."EDU_TEACHER"."SUBJECTID" IS '学科id';
COMMENT ON COLUMN "SCOTT"."EDU_TEACHER"."ISDELETE" IS '是否已删除 0：已删除 1：未删除 默认1';

-- ----------------------------
-- Records of EDU_TEACHER
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_TEACHER_ROLE
-- ----------------------------
DROP TABLE "SCOTT"."EDU_TEACHER_ROLE";
CREATE TABLE "SCOTT"."EDU_TEACHER_ROLE" (
  "TEACHERID" NUMBER NOT NULL,
  "ROLEID" NUMBER NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_TEACHER_ROLE"."TEACHERID" IS '教师id';
COMMENT ON COLUMN "SCOTT"."EDU_TEACHER_ROLE"."ROLEID" IS '角色id';

-- ----------------------------
-- Records of EDU_TEACHER_ROLE
-- ----------------------------

-- ----------------------------
-- Table structure for EDU_USER
-- ----------------------------
DROP TABLE "SCOTT"."EDU_USER";
CREATE TABLE "SCOTT"."EDU_USER" (
  "ID" NUMBER NOT NULL,
  "USERNAME" VARCHAR2(20 CHAR) NOT NULL,
  "PASSWORD" VARCHAR2(20 CHAR) NOT NULL,
  "TYPE" NUMBER(1,0) DEFAULT 0  NOT NULL,
  "ISENABLE" CHAR(1 BYTE) DEFAULT 1  NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EDU_USER"."ID" IS '主键';
COMMENT ON COLUMN "SCOTT"."EDU_USER"."USERNAME" IS '登录名称';
COMMENT ON COLUMN "SCOTT"."EDU_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "SCOTT"."EDU_USER"."TYPE" IS '用户类型 0：管理员 1：老师 2：学生';
COMMENT ON COLUMN "SCOTT"."EDU_USER"."ISENABLE" IS '是否启用 0：未启用 1：已启用  默认1';

-- ----------------------------
-- Records of EDU_USER
-- ----------------------------
INSERT INTO "SCOTT"."EDU_USER" VALUES ('1', 'admin', '123456', '0', '1');

-- ----------------------------
-- Sequence structure for SEQ_ACTION
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_ACTION";
CREATE SEQUENCE "SCOTT"."SEQ_ACTION" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_APPEAL
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_APPEAL";
CREATE SEQUENCE "SCOTT"."SEQ_APPEAL" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_CLASS
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_CLASS";
CREATE SEQUENCE "SCOTT"."SEQ_CLASS" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_EXAM
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_EXAM";
CREATE SEQUENCE "SCOTT"."SEQ_EXAM" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_EXAMDETIAL
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_EXAMDETIAL";
CREATE SEQUENCE "SCOTT"."SEQ_EXAMDETIAL" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_EXAMINE_PAPER
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_EXAMINE_PAPER";
CREATE SEQUENCE "SCOTT"."SEQ_EXAMINE_PAPER" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_EXAMQUESTIONS
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_EXAMQUESTIONS";
CREATE SEQUENCE "SCOTT"."SEQ_EXAMQUESTIONS" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_ROLE
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_ROLE";
CREATE SEQUENCE "SCOTT"."SEQ_ROLE" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_SCOREDETAIL
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_SCOREDETAIL";
CREATE SEQUENCE "SCOTT"."SEQ_SCOREDETAIL" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_STUDENT
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_STUDENT";
CREATE SEQUENCE "SCOTT"."SEQ_STUDENT" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_SUBJECT
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_SUBJECT";
CREATE SEQUENCE "SCOTT"."SEQ_SUBJECT" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_SUGGESTIONS
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_SUGGESTIONS";
CREATE SEQUENCE "SCOTT"."SEQ_SUGGESTIONS" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_TEACHER
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_TEACHER";
CREATE SEQUENCE "SCOTT"."SEQ_TEACHER" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_USER
-- ----------------------------
DROP SEQUENCE "SCOTT"."SEQ_USER";
CREATE SEQUENCE "SCOTT"."SEQ_USER" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 ORDER NOCACHE;

-- ----------------------------
-- Primary Key structure for table EDU_ACTION
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_ACTION" ADD CONSTRAINT "EDU_ACTION_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_ACTION
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_ACTION" ADD CONSTRAINT "SYS_C0010980" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_ACTION" ADD CONSTRAINT "SYS_C0010981" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_ACTION" ADD CONSTRAINT "SYS_C0010982" CHECK ("ISENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_APPEAL
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_APPEAL" ADD CONSTRAINT "EDU_APPEAL_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_APPEAL
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_APPEAL" ADD CONSTRAINT "SYS_C0011035" CHECK ("SCOREDETAILID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_CLASS
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_CLASS" ADD CONSTRAINT "EDU_CLASS_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_CLASS
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_CLASS" ADD CONSTRAINT "SYS_C0010984" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_CLASS" ADD CONSTRAINT "SYS_C0010985" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_CLASS" ADD CONSTRAINT "SYS_C0010986" CHECK ("ISENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_CLASS" ADD CONSTRAINT "SYS_C0010987" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table EDU_CLASS_TEACHER
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_CLASS_TEACHER" ADD CONSTRAINT "SYS_C0010989" CHECK ("TEACHERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_CLASS_TEACHER" ADD CONSTRAINT "SYS_C0010990" CHECK ("CLASSID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_EXAM
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_EXAM" ADD CONSTRAINT "EDU_EXAM_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_EXAM
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_EXAM" ADD CONSTRAINT "SYS_C0010991" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_EXAM" ADD CONSTRAINT "SYS_C0010992" CHECK ("SUBJECTID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_EXAMDETIAL
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_EXAMDETIAL" ADD CONSTRAINT "EDU_EXAMDETIAL_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_EXAMDETIAL
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_EXAMDETIAL" ADD CONSTRAINT "SYS_C0010994" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_EXAMDETIAL" ADD CONSTRAINT "SYS_C0010995" CHECK ("STUDENTID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_EXAMDETIAL" ADD CONSTRAINT "SYS_C0010996" CHECK ("EXAMID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_EXAMINE_PAPER
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_EXAMINE_PAPER" ADD CONSTRAINT "EDU_EXAMINE_PAPER_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table EDU_EXAMQUESTIONS
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_EXAMQUESTIONS" ADD CONSTRAINT "EDU_EXAMQUESTIONS_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table EDU_ROLE
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_ROLE" ADD CONSTRAINT "EDU_ROLE_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_ROLE
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_ROLE" ADD CONSTRAINT "SYS_C0010998" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_ROLE" ADD CONSTRAINT "SYS_C0010999" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_ROLE" ADD CONSTRAINT "SYS_C0011000" CHECK ("ISENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table EDU_ROLE_ACTION
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_ROLE_ACTION" ADD CONSTRAINT "SYS_C0011002" CHECK ("ROLEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_ROLE_ACTION" ADD CONSTRAINT "SYS_C0011003" CHECK ("ACTIONID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_SCOREDETAIL
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_SCOREDETAIL" ADD CONSTRAINT "NEWTABLE_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_SCOREDETAIL
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_SCOREDETAIL" ADD CONSTRAINT "SYS_C0011031" CHECK ("EXAMDETAILID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_SCOREDETAIL" ADD CONSTRAINT "SYS_C0011032" CHECK ("QUESTIONID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_SCOREDETAIL" ADD CONSTRAINT "SYS_C0011033" CHECK ("SCORE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_STUDENT
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_STUDENT" ADD CONSTRAINT "EDU_STUDENT_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_STUDENT
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_STUDENT" ADD CONSTRAINT "SYS_C0011004" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_STUDENT" ADD CONSTRAINT "SYS_C0011005" CHECK ("ISDELETE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_SUBJECT
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_SUBJECT" ADD CONSTRAINT "EDU_SUBJECT_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_SUBJECT
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_SUBJECT" ADD CONSTRAINT "SYS_C0011007" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_SUBJECT" ADD CONSTRAINT "SYS_C0011008" CHECK ("ISENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_SUBJECT" ADD CONSTRAINT "SYS_C0011009" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_SUGGESTIONS
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_SUGGESTIONS" ADD CONSTRAINT "EDU_SUGGESTIONS_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_SUGGESTIONS
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_SUGGESTIONS" ADD CONSTRAINT "SYS_C0011011" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_SUGGESTIONS" ADD CONSTRAINT "SYS_C0011012" CHECK ("TEACHERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_SUGGESTIONS" ADD CONSTRAINT "SYS_C0011013" CHECK ("STUDENTID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_SUGGESTIONS" ADD CONSTRAINT "SYS_C0011014" CHECK ("EXAMDETAILID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_TEACHER
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_TEACHER" ADD CONSTRAINT "EDU_TEACHER_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_TEACHER
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_TEACHER" ADD CONSTRAINT "SYS_C0011016" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_TEACHER" ADD CONSTRAINT "SYS_C0011017" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_TEACHER" ADD CONSTRAINT "SYS_C0011018" CHECK ("USERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_TEACHER" ADD CONSTRAINT "SYS_C0011019" CHECK ("ISDELETE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table EDU_TEACHER_ROLE
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_TEACHER_ROLE" ADD CONSTRAINT "SYS_C0011021" CHECK ("TEACHERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_TEACHER_ROLE" ADD CONSTRAINT "SYS_C0011022" CHECK ("ROLEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDU_USER
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_USER" ADD CONSTRAINT "EDU_USER_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDU_USER
-- ----------------------------
ALTER TABLE "SCOTT"."EDU_USER" ADD CONSTRAINT "SYS_C0011023" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_USER" ADD CONSTRAINT "SYS_C0011024" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_USER" ADD CONSTRAINT "SYS_C0011025" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_USER" ADD CONSTRAINT "SYS_C0011026" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EDU_USER" ADD CONSTRAINT "SYS_C0011027" CHECK ("ISENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
